<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testa" nsURI="http://test-prueba/1.0" nsPrefix="testa">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref4" upperBound="-1" eType="#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref5" upperBound="-1" eType="#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref1" upperBound="-1" eType="#//Container"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" upperBound="-1" eType="#//Container2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref3" upperBound="-1" eType="#//Referent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref6" upperBound="-1" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteClass1" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteClass2" eSuperTypes="#//Element"/>
</ecore:EPackage>
